variable "region" {}
variable "project_name" {}
variable "vpc_cidr" {}
variable "subnet_cidr_block" {}
variable "assign_public_ip" {}
variable "availability_zones" {}
variable "tags" {}
variable "profile" {}
variable "cluster_name" {}
variable "cluster_version" {}
variable "create_node_group" {}
variable "number_of_nodegroups" {}
variable "node_group_name" {}
variable "desired_size" {}
variable "max_size" {}
variable "min_size" {}
variable "ami_type" {}
variable "capacity_type" {}
variable "thumbprint_list" {}
variable "client_id_list" {}
variable "instance_types" {}
